// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Persistance.ContextClasses;

#nullable disable

namespace Project.Persistance.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20260118124539_mig9")]
    partial class mig9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "0782eeb4-160e-4ffb-b61e-4c8a57025d88",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "287913cd-434c-4bce-a7da-3f84d000e46a",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Insan Kaynaklari Muduru",
                            NormalizedName = "INSAN KAYNAKLARI MUDURU",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "869a61d9-cb47-45df-95ef-f90a8cf7ef6a",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Restaurant Muduru",
                            NormalizedName = "RESTAURANT MUDURU",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "690fdafd-6438-4e43-b2ff-1804ad47182b",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mutfak Sefi",
                            NormalizedName = "MUTFAK SEFI",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            ConcurrencyStamp = "e608f4cf-0d29-48b0-93da-741042aaaf3f",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bar Sefi",
                            NormalizedName = "BAR SEFI",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            ConcurrencyStamp = "4e6022b0-4d51-420c-983f-dc585926ac14",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Asci",
                            NormalizedName = "ASCI",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            ConcurrencyStamp = "a56d7ced-6142-4b20-bd1c-662deb7d7401",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Barmen",
                            NormalizedName = "BARMEN",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            ConcurrencyStamp = "025aee1a-fa7a-421a-84f5-ed5693f0f09c",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Garson",
                            NormalizedName = "GARSON",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            ConcurrencyStamp = "5e86de9b-ffd0-4628-8dc0-1693d696250d",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hizmet Personeli",
                            NormalizedName = "HIZMET PERSONELI",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            ConcurrencyStamp = "38f15083-812b-479e-ae4b-e9a6773cc610",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Idari Personel",
                            NormalizedName = "IDARI PERSONEL",
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            ConcurrencyStamp = "6453a284-db6e-4b6d-ad61-a9c2ec7a48ee",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Stajyer",
                            NormalizedName = "STAJYER",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fb1ca947-3d65-4d12-b7d8-947bee5b75cb",
                            Email = "admin@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEHld23ZX0vGkexjXF3JYQCvRM/prCOCSxpRtnmRo/XieMXQzwjuvBGtJST8nqYdpnA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a50b270d-d972-4f8a-bd39-2f4818fccfa5",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "70c294b8-573b-47f0-8571-8d8414c2c5ca",
                            Email = "mudur@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "MUDUR",
                            PasswordHash = "AQAAAAIAAYagAAAAEIxpo763HwETaZl3B+YSJNoonROxV00Kl6nqw39LWy1Q8jgrQJLBMwvVvQT4bOC9vQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4d3f20eb-ab37-48b2-afee-5bad02c1f6ab",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "mudur"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "78c6d9e2-e606-42cb-a896-a799cc1488ef",
                            Email = "insankaynaklari@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "INSANKAYNAKLARI",
                            PasswordHash = "AQAAAAIAAYagAAAAEJvUPE0LRpRxuJdNZlOjtw0hmEDMKCXB3fzHDTG2U2K0uCCpTRoCge6ha1D6oJNzmA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "934a8772-bfea-4c8e-b39e-ae726e381254",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "insankaynaklari"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "087caecd-2314-4c1f-8d6e-55d0f48beb87",
                            Email = "mutfaksef@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "MUTFAKSEF",
                            PasswordHash = "AQAAAAIAAYagAAAAELq+SKbJpD3fFxFxExKy57GcapsMP1atM8CYHTnXAwK2XEWaDjW+b0OQdcX2HOn2FA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3373e86c-3da1-483f-9e6f-468e9edd56be",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "mutfaksef"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fb3ff81b-0cd2-40d0-b8dc-e309bbdbe3a9",
                            Email = "barsef@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "BARSEF",
                            PasswordHash = "AQAAAAIAAYagAAAAEP0+Farg4yNkqqHv5sabzIoAJJg3UNNwM9k3OvrRg2JTnMBo7g9WMn7MWKYAwQY7Yw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a8206fb5-8c52-4f07-8c82-d7a3afd0e8d0",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "barsef"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e6e72d8d-06e5-4b1a-a24a-6c6f79164e5e",
                            Email = "asci@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "ASCI",
                            PasswordHash = "AQAAAAIAAYagAAAAEC3raOnWACKeL1nQdiiwgXAFLEyjR/VNxKwdVCIjnOlDp+Y5IpKeeBJatHBR+aYGXw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1f6745ed-24ec-41a6-88ce-9730a3941620",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "asci"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e6017c82-a41b-439e-b8c6-f78463c1851c",
                            Email = "barmen@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "BARMEN",
                            PasswordHash = "AQAAAAIAAYagAAAAEE4gf6Vn30qU8yS2D6hiZVb8tU69TQOQLBBPMk6S15C2REgswYvfmzRmJacEXbYdBg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dd73ea47-be16-4c1b-9248-8c72a480a19a",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "barmen"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "31855f43-7078-466f-852b-d87615ff5dfd",
                            Email = "garson@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "GARSON",
                            PasswordHash = "AQAAAAIAAYagAAAAEGvX6yUrHGVkj5fw49XUMlFpzQwxYiXMKzwUXGx/J86pMASenID31lZKiasfZAd7og==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "312a6da2-2ce0-4f2d-b2a0-a2466e5142f0",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "garson"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "37bd86ef-1fed-435c-a058-3bf3e9810518",
                            Email = "idaripersonel@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "IDARIPERSONEL",
                            PasswordHash = "AQAAAAIAAYagAAAAEHQ5RKjrjvLzR3b0F7f3bJF0+UvtoDBduaWIHUUpo9OeojSP1aG04OwBTQdVqjvn2A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2f757565-efef-44f4-8b24-0eed39f0fb8d",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "idaripersonel"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a5057980-2237-46c9-8083-22222935e77f",
                            Email = "hizmetpersoneli@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "HIZMETPERSONELI",
                            PasswordHash = "AQAAAAIAAYagAAAAEHJgcMyC/yLb7fOzuFZP4wW0++/HcpudcILQ5HR9uulHClY1J7MbcSs1/PunPShQmg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "97b92b98-fe37-423b-9f23-993240f5523d",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "hizmetpersoneli"
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a52a111b-2821-47a7-9258-b714d08fee17",
                            Email = "stajyer@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "STAJYER",
                            PasswordHash = "AQAAAAIAAYagAAAAEG0p3Z/ATM+RLzoD+2M3+Oven4zO25YyQ2T2kyRyTeft1Tc7P4YjUT49MYC9PEHsNg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "95466361-2038-4412-8b1a-6757fe69c88e",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "stajyer"
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.AppUserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("money");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TCKNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("AppUserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = 1,
                            BirthDate = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ahmet",
                            HireDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Yılmaz",
                            Salary = 2147483647m,
                            Status = 1,
                            TCKNo = "12345678901"
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = 2,
                            BirthDate = new DateTime(1985, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mehmet",
                            HireDate = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Demir",
                            Salary = 150000m,
                            Status = 1,
                            TCKNo = "10987654321"
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = 3,
                            BirthDate = new DateTime(1992, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ayşe",
                            HireDate = new DateTime(2022, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kara",
                            Salary = 120000m,
                            Status = 1,
                            TCKNo = "23456789012"
                        },
                        new
                        {
                            Id = 4,
                            AppUserId = 4,
                            BirthDate = new DateTime(1995, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Fatma",
                            HireDate = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Çelik",
                            Salary = 115000m,
                            Status = 1,
                            TCKNo = "34567890123"
                        },
                        new
                        {
                            Id = 5,
                            AppUserId = 5,
                            BirthDate = new DateTime(1993, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ali",
                            HireDate = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Şahin",
                            Salary = 110000m,
                            Status = 1,
                            TCKNo = "45678901234"
                        },
                        new
                        {
                            Id = 6,
                            AppUserId = 6,
                            BirthDate = new DateTime(1996, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Zeynep",
                            HireDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Yıldız",
                            Salary = 90000m,
                            Status = 1,
                            TCKNo = "56789012345"
                        },
                        new
                        {
                            Id = 7,
                            AppUserId = 7,
                            BirthDate = new DateTime(1994, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Can",
                            HireDate = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Polat",
                            Salary = 85000m,
                            Status = 1,
                            TCKNo = "67890123456"
                        },
                        new
                        {
                            Id = 8,
                            AppUserId = 8,
                            BirthDate = new DateTime(1997, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Elif",
                            HireDate = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Aydın",
                            Salary = 80000m,
                            Status = 1,
                            TCKNo = "78901234567"
                        },
                        new
                        {
                            Id = 9,
                            AppUserId = 9,
                            BirthDate = new DateTime(1991, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mert",
                            HireDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kılıç",
                            Salary = 95000m,
                            Status = 1,
                            TCKNo = "89012345678"
                        },
                        new
                        {
                            Id = 10,
                            AppUserId = 10,
                            BirthDate = new DateTime(1988, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Seda",
                            HireDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Güneş",
                            Salary = 105000m,
                            Status = 1,
                            TCKNo = "90123456789"
                        },
                        new
                        {
                            Id = 11,
                            AppUserId = 11,
                            BirthDate = new DateTime(2000, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Burak",
                            HireDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Arslan",
                            Salary = 60000m,
                            Status = 1,
                            TCKNo = "01234567890"
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            Id = 1,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2,
                            Id = 2,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3,
                            Id = 3,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4,
                            Id = 4,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 5,
                            Id = 5,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 6,
                            Id = 6,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 7,
                            Id = 7,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 8,
                            Id = 8,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 9,
                            RoleId = 9,
                            Id = 9,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 10,
                            Id = 10,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 11,
                            RoleId = 11,
                            Id = 11,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Yiyecekler",
                            Description = "Ana Gıda Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "İçecekler",
                            Description = "Ana İçecek Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Sarf Malzemeleri",
                            Description = "Ana Sarf Malzemeleri Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "DemirBaş",
                            Description = "Ana DemirBaş Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Etler",
                            Description = "Et Ürünleri Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Sebzeler",
                            Description = "Sebze Ürünleri Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Meyveler",
                            Description = "Meyve Ürünleri Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Alkollü İçecekler",
                            Description = "Alkollü İçecek Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Alkolsüz İçecekler",
                            Description = "Alkolsüz İçecek Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Temizlik Malzemeleri",
                            Description = "Temizlik Malzemeleri Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryName = "Ofis Malzemeleri",
                            Description = "Ofis Malzemeleri Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryName = "Mutfak Ekipmanları",
                            Description = "Mutfak Ekipmanları Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryName = "Mobilyalar",
                            Description = "Mobilya Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 4,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderState")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("money");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WaiterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.HasIndex("WaiterId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedDate = new DateTime(2026, 1, 18, 15, 45, 37, 703, DateTimeKind.Local).AddTicks(1991),
                            OrderDate = new DateTime(2026, 1, 18, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            OrderState = 1,
                            Status = 1,
                            TableId = 1,
                            TotalPrice = 250m,
                            WaiterId = 2
                        },
                        new
                        {
                            Id = 2,
                            InsertedDate = new DateTime(2026, 1, 18, 15, 45, 37, 703, DateTimeKind.Local).AddTicks(2004),
                            OrderDate = new DateTime(2026, 1, 18, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderState = 1,
                            Status = 1,
                            TableId = 2,
                            TotalPrice = 180m,
                            WaiterId = 3
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DetailState")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("OrderId", "ProductId")
                        .IsUnique();

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DetailState = 0,
                            InsertedDate = new DateTime(2026, 1, 18, 15, 45, 37, 703, DateTimeKind.Local).AddTicks(1867),
                            OrderId = 1,
                            ProductId = 5,
                            Quantity = 1,
                            Status = 1,
                            UnitPrice = 200m
                        },
                        new
                        {
                            Id = 2,
                            DetailState = 0,
                            InsertedDate = new DateTime(2026, 1, 18, 15, 45, 37, 703, DateTimeKind.Local).AddTicks(1878),
                            OrderId = 1,
                            ProductId = 8,
                            Quantity = 1,
                            Status = 1,
                            UnitPrice = 50m
                        },
                        new
                        {
                            Id = 3,
                            DetailState = 0,
                            InsertedDate = new DateTime(2026, 1, 18, 15, 45, 37, 703, DateTimeKind.Local).AddTicks(1883),
                            OrderId = 2,
                            ProductId = 6,
                            Quantity = 2,
                            Status = 1,
                            UnitPrice = 90m
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanBeProduced")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSellable")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanBeProduced = false,
                            CategoryId = 5,
                            InsertedDate = new DateTime(2026, 1, 18, 15, 45, 37, 703, DateTimeKind.Local).AddTicks(1203),
                            IsSellable = true,
                            ProductName = "Dana Bonfile",
                            Status = 1,
                            UnitId = 1,
                            UnitPrice = 500m
                        },
                        new
                        {
                            Id = 2,
                            CanBeProduced = false,
                            CategoryId = 5,
                            InsertedDate = new DateTime(2026, 1, 18, 15, 45, 37, 703, DateTimeKind.Local).AddTicks(1267),
                            IsSellable = true,
                            ProductName = "Tavuk Göğsü",
                            Status = 1,
                            UnitId = 1,
                            UnitPrice = 150m
                        },
                        new
                        {
                            Id = 3,
                            CanBeProduced = false,
                            CategoryId = 6,
                            InsertedDate = new DateTime(2026, 1, 18, 15, 45, 37, 703, DateTimeKind.Local).AddTicks(1272),
                            IsSellable = true,
                            ProductName = "Marul",
                            Status = 1,
                            UnitId = 2,
                            UnitPrice = 20m
                        },
                        new
                        {
                            Id = 4,
                            CanBeProduced = false,
                            CategoryId = 6,
                            InsertedDate = new DateTime(2026, 1, 18, 15, 45, 37, 703, DateTimeKind.Local).AddTicks(1277),
                            IsSellable = true,
                            ProductName = "Domates",
                            Status = 1,
                            UnitId = 1,
                            UnitPrice = 25m
                        },
                        new
                        {
                            Id = 5,
                            CanBeProduced = false,
                            CategoryId = 7,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Elma",
                            Status = 1,
                            UnitId = 1,
                            UnitPrice = 30m
                        },
                        new
                        {
                            Id = 6,
                            CanBeProduced = false,
                            CategoryId = 7,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Muz",
                            Status = 1,
                            UnitId = 1,
                            UnitPrice = 40m
                        },
                        new
                        {
                            Id = 7,
                            CanBeProduced = false,
                            CategoryId = 8,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Kola",
                            Status = 1,
                            UnitId = 3,
                            UnitPrice = 15m
                        },
                        new
                        {
                            Id = 8,
                            CanBeProduced = false,
                            CategoryId = 8,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Gazoz",
                            Status = 1,
                            UnitId = 3,
                            UnitPrice = 12m
                        },
                        new
                        {
                            Id = 9,
                            CanBeProduced = false,
                            CategoryId = 9,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Ayran",
                            Status = 1,
                            UnitId = 3,
                            UnitPrice = 10m
                        },
                        new
                        {
                            Id = 10,
                            CanBeProduced = false,
                            CategoryId = 9,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Meyve Suyu",
                            Status = 1,
                            UnitId = 3,
                            UnitPrice = 18m
                        },
                        new
                        {
                            Id = 11,
                            CanBeProduced = false,
                            CategoryId = 10,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Deterjan",
                            Status = 1,
                            UnitId = 4,
                            UnitPrice = 60m
                        },
                        new
                        {
                            Id = 12,
                            CanBeProduced = false,
                            CategoryId = 10,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Çamaşır Suyu",
                            Status = 1,
                            UnitId = 4,
                            UnitPrice = 25m
                        },
                        new
                        {
                            Id = 13,
                            CanBeProduced = false,
                            CategoryId = 11,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Kalem",
                            Status = 1,
                            UnitId = 4,
                            UnitPrice = 2m
                        },
                        new
                        {
                            Id = 14,
                            CanBeProduced = false,
                            CategoryId = 11,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Defter",
                            Status = 1,
                            UnitId = 2,
                            UnitPrice = 15m
                        },
                        new
                        {
                            Id = 15,
                            CanBeProduced = false,
                            CategoryId = 12,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Tencere",
                            Status = 1,
                            UnitId = 2,
                            UnitPrice = 200m
                        },
                        new
                        {
                            Id = 16,
                            CanBeProduced = false,
                            CategoryId = 12,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Bıçak Seti",
                            Status = 1,
                            UnitId = 2,
                            UnitPrice = 150m
                        },
                        new
                        {
                            Id = 17,
                            CanBeProduced = false,
                            CategoryId = 13,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Sandalye",
                            Status = 1,
                            UnitId = 2,
                            UnitPrice = 300m
                        },
                        new
                        {
                            Id = 18,
                            CanBeProduced = false,
                            CategoryId = 13,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Masa",
                            Status = 1,
                            UnitId = 2,
                            UnitPrice = 700m
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.RecipeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UnitId");

                    b.ToTable("RecipeItems");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.StockTransAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("TransActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("StockTransActions");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "İkitelli OSB, İstanbul",
                            ContactName = "Ali Yıldız",
                            Email = "info@lezzettedarik.com",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+90 (212) 555 0101",
                            Status = 1,
                            SupplierName = "Lezzet Tedarik A.Ş."
                        },
                        new
                        {
                            Id = 2,
                            Address = "Gaziemir, İzmir",
                            ContactName = "Ayşe Demir",
                            Email = "siparis@mutfakmalzemeleri.com",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+90 (232) 555 0202",
                            Status = 1,
                            SupplierName = "Mutfak Malzemeleri Ltd."
                        },
                        new
                        {
                            Id = 3,
                            Address = "Çankaya, Ankara",
                            ContactName = "Mehmet Kaya",
                            Email = "iletisim@dogalurunler.org",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+90 (312) 555 0303",
                            Status = 1,
                            SupplierName = "Doğal Ürünler Kooperatifi"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Kartal, İstanbul",
                            ContactName = "Zeynep Çelik",
                            Email = "destek@icecekmerkezi.com",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+90 (216) 555 0404",
                            Status = 1,
                            SupplierName = "İçecek Merkezi"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Beşiktaş, İstanbul",
                            ContactName = "Cengiz Ak",
                            Email = "tedarik@kafebar.com",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+90 (212) 555 0707",
                            Status = 1,
                            SupplierName = "Kafe & Bar Tedarik"
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WaiterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WaiterId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TableNumber = "Masa 1",
                            TableStatus = 0
                        },
                        new
                        {
                            Id = 2,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TableNumber = "Masa 2",
                            TableStatus = 0
                        },
                        new
                        {
                            Id = 3,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TableNumber = "Masa 3",
                            TableStatus = 0
                        },
                        new
                        {
                            Id = 4,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TableNumber = "Masa 4",
                            TableStatus = 0
                        },
                        new
                        {
                            Id = 5,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TableNumber = "Masa 5",
                            TableStatus = 0
                        },
                        new
                        {
                            Id = 6,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TableNumber = "Masa 6",
                            TableStatus = 0
                        },
                        new
                        {
                            Id = 7,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TableNumber = "Masa 7",
                            TableStatus = 0
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UnitAbbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            UnitAbbreviation = "kg",
                            UnitName = "Kilogram"
                        },
                        new
                        {
                            Id = 2,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            UnitAbbreviation = "ad",
                            UnitName = "Adet"
                        },
                        new
                        {
                            Id = 3,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            UnitAbbreviation = "lt",
                            UnitName = "Litre"
                        },
                        new
                        {
                            Id = 4,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            UnitAbbreviation = "pkt",
                            UnitName = "Paket"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.AppUserProfile", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.AppUser", "AppUser")
                        .WithOne("AppUserProfile")
                        .HasForeignKey("Project.Domain.Entities.Concretes.AppUserProfile", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.AppUserRole", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Category", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Order", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.Table", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.AppUser", "Waiter")
                        .WithMany("Orders")
                        .HasForeignKey("WaiterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Table");

                    b.Navigation("Waiter");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.OrderDetail", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Product", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.Unit", "Unit")
                        .WithMany("Products")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Recipe", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.Product", "Product")
                        .WithOne("Recipe")
                        .HasForeignKey("Project.Domain.Entities.Concretes.Recipe", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.RecipeItem", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.Product", "Product")
                        .WithMany("RecipeItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.Recipe", "Recipe")
                        .WithMany("RecipeItems")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.Unit", "Unit")
                        .WithMany("RecipeItems")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.StockTransAction", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.AppUser", "User")
                        .WithMany("StockTransActions")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.Product", "Product")
                        .WithMany("StockTransActions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.Supplier", "Supplier")
                        .WithMany("StockTransActions")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("Supplier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Table", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.AppUser", "Waiter")
                        .WithMany("Tables")
                        .HasForeignKey("WaiterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Waiter");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.AppUser", b =>
                {
                    b.Navigation("AppUserProfile")
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("StockTransActions");

                    b.Navigation("Tables");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Recipes");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Product", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Recipe")
                        .IsRequired();

                    b.Navigation("RecipeItems");

                    b.Navigation("StockTransActions");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Recipe", b =>
                {
                    b.Navigation("RecipeItems");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Supplier", b =>
                {
                    b.Navigation("StockTransActions");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Table", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Unit", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("RecipeItems");
                });
#pragma warning restore 612, 618
        }
    }
}
