// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Persistance.ContextClasses;

#nullable disable

namespace Project.Persistance.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "be28c748-40d0-4161-af38-977b3fe3608b",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "43959260-c5eb-4916-828f-0fb30d22e093",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "İnsan Kaynakları Müdürü",
                            NormalizedName = "İNSAN KAYNAKLARI MÜDÜRÜ",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "123bc3e1-add8-4136-a5d6-76b18834199c",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Restaurant Müdürü",
                            NormalizedName = "RESTAURANT MÜDÜRÜ",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "45ef3670-7d0d-4aa8-bafc-eddd2dc04a72",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mutfak Şefi",
                            NormalizedName = "MUTFAK ŞEFİ",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            ConcurrencyStamp = "069941b4-50ac-474c-8465-ca3213293dcd",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bar Şefi",
                            NormalizedName = "BAR ŞEFİ",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            ConcurrencyStamp = "b1b8e549-d662-4374-b1b5-da1e33a872e9",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aşçı",
                            NormalizedName = "AŞÇI",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            ConcurrencyStamp = "00b22760-bc8b-43b4-bda2-e18a8c8a9b7c",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Barmen",
                            NormalizedName = "BARMEN",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            ConcurrencyStamp = "f48a1e83-6ac2-44e8-b90c-b60e74656d2b",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "garson",
                            NormalizedName = "GARSON",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            ConcurrencyStamp = "d0004a53-862c-45a4-a59e-002a972fcf6a",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hizmet Personeli",
                            NormalizedName = "HİZMET PERSONELİ",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            ConcurrencyStamp = "03c00d72-3f1b-4987-b3a7-8a4978c0bb2a",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "İdari Personel",
                            NormalizedName = "İDARİ PERSONEL",
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            ConcurrencyStamp = "aa5b3905-0f04-4987-81e9-44cf801dbcee",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Stajyer",
                            NormalizedName = "STAJYER",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bd2d3f8d-ed12-4ed3-8b0d-06a108d606fe",
                            Email = "admin@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEGTPAaGYblWwF4SB1RjLTrsI9y+d82G2sg3mulr1KVGCVQyDYJF+/1k9JE2+5ustOg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "60e41f6f-3ec2-4905-b29d-fd2f477db921",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "46486b3a-6ee4-455b-a72e-63605fce245f",
                            Email = "mudur@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "MÜDÜR",
                            PasswordHash = "AQAAAAIAAYagAAAAEAJAK1JbWX6FLrIb+oiMJoKsa49Hk0HrFyicpFdPa+9dY85qHJRkrPRw/+8g3G1Q6Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c32e7a8b-0915-44d7-bd41-e75a4c96a397",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "müdür"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7d96d85b-2873-4ef4-8c04-311fc8c97b7f",
                            Email = "insankaynaklari@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "INSANKAYNAKLARI",
                            PasswordHash = "AQAAAAIAAYagAAAAEL+tGoz76ny1o2SCtOkiQn4BpI4x5KA61JV3s0kpglex98MtmPEX303LfstJvzQgQg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d605cdd8-b699-4b3e-9448-227e737c5e41",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "insankaynaklari"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a7d27b48-0ea1-478e-8977-35699ed3b03f",
                            Email = "mutfakşef@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "MUTFAKŞEF",
                            PasswordHash = "AQAAAAIAAYagAAAAEMbXOIako1ITdY3YtBxIRMhqZGngDdsk/v0/k55R2xkNwj6zhBNIj5h/osiX//Nn/w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "94f4a6ab-2989-4e7e-b3b1-4c27a70f1349",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "mutfakşef"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ca20f5e4-73bc-4ef8-8364-c45eb8f7723b",
                            Email = "barşef@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "BARŞEF",
                            PasswordHash = "AQAAAAIAAYagAAAAEEXEJ8ra1eCmgxBnRsKM/Q/BTLI+rkVTe+6ehZ5563DaIT8RH+oJSXHhh76CdbGh/Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "08ef8353-488e-4228-a8c5-022127dc9ef9",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "barşef"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "17416624-8c83-4583-b2a2-9eba6680aef2",
                            Email = "aşçı@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "AŞÇI",
                            PasswordHash = "AQAAAAIAAYagAAAAEHVY3SVUFGH68+SzUBpmwK+V0cjE+y0d8agTaWFtPGYC6ux6YffNHXLfcqa5CKiUhw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "30379c70-7d83-4253-a1a8-1bd16964d4ea",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "aşçı"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6f61f37a-8646-4fdb-a688-fd314a6ff2e2",
                            Email = "barmen@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "BARMEN",
                            PasswordHash = "AQAAAAIAAYagAAAAEOfxtQF+eUMpi9B3f/JwOGLa0VIQiboFbhoh9xApyXQI+y7vAP1VM7LeJ/0OS686nw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fb41bf7b-f6ae-492f-b7c0-ac888d166dca",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "barmen"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e14f88f9-ad61-4d53-827a-05c3b904799a",
                            Email = "garson@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "GARSON",
                            PasswordHash = "AQAAAAIAAYagAAAAEEsfBxnFOrh2Opo588kQ9w8nlx0Jz10gLdgXt28w5rZm4EQYrks4uwGuo3UskcVZ6A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c9a0ca1d-997e-4a31-92a9-53f16478ddb5",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "garson"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b63c9788-acb9-437b-800d-0e43fb30b41e",
                            Email = "idaripersonel@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "IDARIPERSONEL",
                            PasswordHash = "AQAAAAIAAYagAAAAELNfjBPZ6ukSd+2U1PiHmWYnR8jknjzD1eJj0BtgEFrXYso8ITkL8Npsl29JV9RhKw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0a888d63-b69a-4db1-89c5-f727d35f635b",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "idaripersonel"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7e7bf340-6f56-4ba6-9428-1b50b046aae8",
                            Email = "hizmetpersoneli@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "HIZMETPERSONELI",
                            PasswordHash = "AQAAAAIAAYagAAAAEPFL3s0QEgyNEubD77brlfUf3NTUGR9/4kt4PuR15+laq7gPxU4ZQ+y+5DoGqyhi8g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "49c1ae59-d4d4-4e4c-9b25-d763c5c20465",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "hizmetpersoneli"
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ed3edd63-dcc8-4187-9d30-b09ec339c14b",
                            Email = "stajyer@restaurantmanagement.com",
                            EmailConfirmed = true,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "STAJYER",
                            PasswordHash = "AQAAAAIAAYagAAAAEFQRfM8NPXgMRN3ciG3XaVKqPS3keuhD6W34mEjvXQmi4xVEOsraUHd7KpOAEslAww==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4762eb14-23e2-44cc-966d-b565b78bbf1e",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "stajyer"
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.AppUserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("money");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TCKNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("AppUserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = 1,
                            BirthDate = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ahmet",
                            HireDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Yılmaz",
                            Salary = 2147483647m,
                            Status = 1,
                            TCKNo = "12345678901"
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = 2,
                            BirthDate = new DateTime(1985, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mehmet",
                            HireDate = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Demir",
                            Salary = 150000m,
                            Status = 1,
                            TCKNo = "10987654321"
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = 3,
                            BirthDate = new DateTime(1992, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ayşe",
                            HireDate = new DateTime(2022, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kara",
                            Salary = 120000m,
                            Status = 1,
                            TCKNo = "23456789012"
                        },
                        new
                        {
                            Id = 4,
                            AppUserId = 4,
                            BirthDate = new DateTime(1995, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Fatma",
                            HireDate = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Çelik",
                            Salary = 115000m,
                            Status = 1,
                            TCKNo = "34567890123"
                        },
                        new
                        {
                            Id = 5,
                            AppUserId = 5,
                            BirthDate = new DateTime(1993, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ali",
                            HireDate = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Şahin",
                            Salary = 110000m,
                            Status = 1,
                            TCKNo = "45678901234"
                        },
                        new
                        {
                            Id = 6,
                            AppUserId = 6,
                            BirthDate = new DateTime(1996, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Zeynep",
                            HireDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Yıldız",
                            Salary = 90000m,
                            Status = 1,
                            TCKNo = "56789012345"
                        },
                        new
                        {
                            Id = 7,
                            AppUserId = 7,
                            BirthDate = new DateTime(1994, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Can",
                            HireDate = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Polat",
                            Salary = 85000m,
                            Status = 1,
                            TCKNo = "67890123456"
                        },
                        new
                        {
                            Id = 8,
                            AppUserId = 8,
                            BirthDate = new DateTime(1997, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Elif",
                            HireDate = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Aydın",
                            Salary = 80000m,
                            Status = 1,
                            TCKNo = "78901234567"
                        },
                        new
                        {
                            Id = 9,
                            AppUserId = 9,
                            BirthDate = new DateTime(1991, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mert",
                            HireDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kılıç",
                            Salary = 95000m,
                            Status = 1,
                            TCKNo = "89012345678"
                        },
                        new
                        {
                            Id = 10,
                            AppUserId = 10,
                            BirthDate = new DateTime(1988, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Seda",
                            HireDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Güneş",
                            Salary = 105000m,
                            Status = 1,
                            TCKNo = "90123456789"
                        },
                        new
                        {
                            Id = 11,
                            AppUserId = 11,
                            BirthDate = new DateTime(2000, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Burak",
                            HireDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Arslan",
                            Salary = 60000m,
                            Status = 1,
                            TCKNo = "01234567890"
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            Id = 1,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2,
                            Id = 2,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3,
                            Id = 3,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4,
                            Id = 4,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 5,
                            Id = 5,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 6,
                            Id = 6,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 7,
                            Id = 7,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 8,
                            Id = 8,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 9,
                            RoleId = 9,
                            Id = 9,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 10,
                            Id = 10,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            UserId = 11,
                            RoleId = 11,
                            Id = 11,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Yiyecekler",
                            Description = "Ana Gıda Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "İçecekler",
                            Description = "Ana İçecek Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Sarf Malzemeleri",
                            Description = "Ana Sarf Malzemeleri Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "DemirBaş",
                            Description = "Ana DemirBaş Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Etler",
                            Description = "Et Ürünleri Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Sebzeler",
                            Description = "Sebze Ürünleri Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Meyveler",
                            Description = "Meyve Ürünleri Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Alkollü İçecekler",
                            Description = "Alkollü İçecek Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Alkolsüz İçecekler",
                            Description = "Alkolsüz İçecek Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Temizlik Malzemeleri",
                            Description = "Temizlik Malzemeleri Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryName = "Ofis Malzemeleri",
                            Description = "Ofis Malzemeleri Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryName = "Mutfak Ekipmanları",
                            Description = "Mutfak Ekipmanları Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryName = "Mobilyalar",
                            Description = "Mobilya Kategorisi",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = 4,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("money");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WaiterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.HasIndex("WaiterId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("OrderId", "ProductId")
                        .IsUnique();

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanBeProduced")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSellable")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanBeProduced = false,
                            CategoryId = 5,
                            InsertedDate = new DateTime(2026, 1, 15, 16, 38, 14, 575, DateTimeKind.Local).AddTicks(2935),
                            IsSellable = true,
                            ProductName = "Dana Bonfile",
                            Status = 1,
                            UnitId = 1,
                            UnitPrice = 500m
                        },
                        new
                        {
                            Id = 2,
                            CanBeProduced = false,
                            CategoryId = 5,
                            InsertedDate = new DateTime(2026, 1, 15, 16, 38, 14, 575, DateTimeKind.Local).AddTicks(2970),
                            IsSellable = true,
                            ProductName = "Tavuk Göğsü",
                            Status = 1,
                            UnitId = 1,
                            UnitPrice = 150m
                        },
                        new
                        {
                            Id = 3,
                            CanBeProduced = false,
                            CategoryId = 6,
                            InsertedDate = new DateTime(2026, 1, 15, 16, 38, 14, 575, DateTimeKind.Local).AddTicks(2974),
                            IsSellable = true,
                            ProductName = "Marul",
                            Status = 1,
                            UnitId = 2,
                            UnitPrice = 20m
                        },
                        new
                        {
                            Id = 4,
                            CanBeProduced = false,
                            CategoryId = 6,
                            InsertedDate = new DateTime(2026, 1, 15, 16, 38, 14, 575, DateTimeKind.Local).AddTicks(2978),
                            IsSellable = true,
                            ProductName = "Domates",
                            Status = 1,
                            UnitId = 1,
                            UnitPrice = 25m
                        },
                        new
                        {
                            Id = 5,
                            CanBeProduced = false,
                            CategoryId = 7,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Elma",
                            Status = 1,
                            UnitId = 1,
                            UnitPrice = 30m
                        },
                        new
                        {
                            Id = 6,
                            CanBeProduced = false,
                            CategoryId = 7,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Muz",
                            Status = 1,
                            UnitId = 1,
                            UnitPrice = 40m
                        },
                        new
                        {
                            Id = 7,
                            CanBeProduced = false,
                            CategoryId = 8,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Kola",
                            Status = 1,
                            UnitId = 3,
                            UnitPrice = 15m
                        },
                        new
                        {
                            Id = 8,
                            CanBeProduced = false,
                            CategoryId = 8,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Gazoz",
                            Status = 1,
                            UnitId = 3,
                            UnitPrice = 12m
                        },
                        new
                        {
                            Id = 9,
                            CanBeProduced = false,
                            CategoryId = 9,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Ayran",
                            Status = 1,
                            UnitId = 3,
                            UnitPrice = 10m
                        },
                        new
                        {
                            Id = 10,
                            CanBeProduced = false,
                            CategoryId = 9,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Meyve Suyu",
                            Status = 1,
                            UnitId = 3,
                            UnitPrice = 18m
                        },
                        new
                        {
                            Id = 11,
                            CanBeProduced = false,
                            CategoryId = 10,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Deterjan",
                            Status = 1,
                            UnitId = 4,
                            UnitPrice = 60m
                        },
                        new
                        {
                            Id = 12,
                            CanBeProduced = false,
                            CategoryId = 10,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Çamaşır Suyu",
                            Status = 1,
                            UnitId = 4,
                            UnitPrice = 25m
                        },
                        new
                        {
                            Id = 13,
                            CanBeProduced = false,
                            CategoryId = 11,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Kalem",
                            Status = 1,
                            UnitId = 4,
                            UnitPrice = 2m
                        },
                        new
                        {
                            Id = 14,
                            CanBeProduced = false,
                            CategoryId = 11,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Defter",
                            Status = 1,
                            UnitId = 2,
                            UnitPrice = 15m
                        },
                        new
                        {
                            Id = 15,
                            CanBeProduced = false,
                            CategoryId = 12,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Tencere",
                            Status = 1,
                            UnitId = 2,
                            UnitPrice = 200m
                        },
                        new
                        {
                            Id = 16,
                            CanBeProduced = false,
                            CategoryId = 12,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Bıçak Seti",
                            Status = 1,
                            UnitId = 2,
                            UnitPrice = 150m
                        },
                        new
                        {
                            Id = 17,
                            CanBeProduced = false,
                            CategoryId = 13,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Sandalye",
                            Status = 1,
                            UnitId = 2,
                            UnitPrice = 300m
                        },
                        new
                        {
                            Id = 18,
                            CanBeProduced = false,
                            CategoryId = 13,
                            InsertedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSellable = true,
                            ProductName = "Masa",
                            Status = 1,
                            UnitId = 2,
                            UnitPrice = 700m
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.RecipeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UnitId");

                    b.ToTable("RecipeItems");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.StockTransAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("TransActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("StockTransActions");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "İkitelli OSB, İstanbul",
                            ContactName = "Ali Yıldız",
                            Email = "info@lezzettedarik.com",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+90 (212) 555 0101",
                            Status = 1,
                            SupplierName = "Lezzet Tedarik A.Ş."
                        },
                        new
                        {
                            Id = 2,
                            Address = "Gaziemir, İzmir",
                            ContactName = "Ayşe Demir",
                            Email = "siparis@mutfakmalzemeleri.com",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+90 (232) 555 0202",
                            Status = 1,
                            SupplierName = "Mutfak Malzemeleri Ltd."
                        },
                        new
                        {
                            Id = 3,
                            Address = "Çankaya, Ankara",
                            ContactName = "Mehmet Kaya",
                            Email = "iletisim@dogalurunler.org",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+90 (312) 555 0303",
                            Status = 1,
                            SupplierName = "Doğal Ürünler Kooperatifi"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Kartal, İstanbul",
                            ContactName = "Zeynep Çelik",
                            Email = "destek@icecekmerkezi.com",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+90 (216) 555 0404",
                            Status = 1,
                            SupplierName = "İçecek Merkezi"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Beşiktaş, İstanbul",
                            ContactName = "Cengiz Ak",
                            Email = "tedarik@kafebar.com",
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+90 (212) 555 0707",
                            Status = 1,
                            SupplierName = "Kafe & Bar Tedarik"
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WaiterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WaiterId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TableNumber = "Masa 1",
                            TableStatus = 0
                        },
                        new
                        {
                            Id = 2,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TableNumber = "Masa 2",
                            TableStatus = 0
                        },
                        new
                        {
                            Id = 3,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TableNumber = "Masa 3",
                            TableStatus = 0
                        },
                        new
                        {
                            Id = 4,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TableNumber = "Masa 4",
                            TableStatus = 0
                        },
                        new
                        {
                            Id = 5,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TableNumber = "Masa 5",
                            TableStatus = 0
                        },
                        new
                        {
                            Id = 6,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TableNumber = "Masa 6",
                            TableStatus = 0
                        },
                        new
                        {
                            Id = 7,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TableNumber = "Masa 7",
                            TableStatus = 0
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UnitAbbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            UnitAbbreviation = "kg",
                            UnitName = "Kilogram"
                        },
                        new
                        {
                            Id = 2,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            UnitAbbreviation = "ad",
                            UnitName = "Adet"
                        },
                        new
                        {
                            Id = 3,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            UnitAbbreviation = "lt",
                            UnitName = "Litre"
                        },
                        new
                        {
                            Id = 4,
                            InsertedDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            UnitAbbreviation = "pkt",
                            UnitName = "Paket"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.AppUserProfile", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.AppUser", "AppUser")
                        .WithOne("AppUserProfile")
                        .HasForeignKey("Project.Domain.Entities.Concretes.AppUserProfile", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.AppUserRole", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Category", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Order", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.Table", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.AppUser", "Waiter")
                        .WithMany("Orders")
                        .HasForeignKey("WaiterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Table");

                    b.Navigation("Waiter");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.OrderDetail", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Product", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.Unit", "Unit")
                        .WithMany("Products")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Recipe", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.Product", "Product")
                        .WithOne("Recipe")
                        .HasForeignKey("Project.Domain.Entities.Concretes.Recipe", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.RecipeItem", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.Product", "Product")
                        .WithMany("RecipeItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.Recipe", "Recipe")
                        .WithMany("RecipeItems")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.Unit", "Unit")
                        .WithMany("RecipeItems")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.StockTransAction", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.AppUser", "User")
                        .WithMany("StockTransActions")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.Product", "Product")
                        .WithMany("StockTransActions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Concretes.Supplier", "Supplier")
                        .WithMany("StockTransActions")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("Supplier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Table", b =>
                {
                    b.HasOne("Project.Domain.Entities.Concretes.AppUser", "Waiter")
                        .WithMany("Tables")
                        .HasForeignKey("WaiterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Waiter");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.AppUser", b =>
                {
                    b.Navigation("AppUserProfile")
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("StockTransActions");

                    b.Navigation("Tables");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Recipes");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Product", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Recipe")
                        .IsRequired();

                    b.Navigation("RecipeItems");

                    b.Navigation("StockTransActions");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Recipe", b =>
                {
                    b.Navigation("RecipeItems");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Supplier", b =>
                {
                    b.Navigation("StockTransActions");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Table", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Project.Domain.Entities.Concretes.Unit", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("RecipeItems");
                });
#pragma warning restore 612, 618
        }
    }
}
